import argparse
def auto_pointer_dssm_arguments(parser):
    parser.add_argument("--data_set", default='demo', type=str, help="Currently, this can be wizard, reddit or de_en")
    parser.add_argument("--exp_name", default='auto_pointer_dssm', type=str, help="The experiment name.")
    parser.add_argument("--epochs", default=100, type=int, help="Epoch numbers.")
    parser.add_argument("--batch_size", default=64,type=int, help="Batch size.")
    parser.add_argument("--src_seq_length", default=35,type=int, help="Source sequence length")
    parser.add_argument("--sample_seq_length", default=35,type=int, help="Positive and Negative sample sequence length")
    parser.add_argument("--semantic_dim", default=300, type=int, help="Semantic embedding size.")
    parser.add_argument("--positive_number", default=1,type=int, help="How many positive samples for training.")
    parser.add_argument("--negative_number", default=4,type=int, help="How many negative samples for training.")
    parser.add_argument("--query_retrieval_number", default=50,type=int, help="How many query retrieval knowledge to do the multi-hop.")
    parser.add_argument("--multi_hop_number", default=6,type=int, help="How many multi-hops.")
    parser.add_argument("--test_top_k", default=50,type=int, help="How many top samples for testing.")
    parser.add_argument("--transformer_depth", default=1, type=int, help="The Transformer Depth.")
    parser.add_argument("--num_heads", default=4, type=int, help="The Transformer Heads.")
    parser.add_argument("--embedding_dim", default=300, type=int, help="The Transformer Embedding dimension.")
    parser.add_argument("--max_pooling_filter_length", default=3, type=int, help="The Filter Length of Max Pooling.")
    parser.add_argument("--vocab_size", default=50000, type=int, help="The vocabulary size.")
    parser.add_argument("--auto_pointer_rate", default=0.7, type=float, help="The split rate between query and auto-pointer.")
    parser.add_argument("--early_stop_patience", default=3, type=int, help="Indicate how many step to show current loss.")
    parser.add_argument("--lr_decay_patience", default=2, type=float, help="When lr doesn't change, it begin to decay'.")
    parser.add_argument("--lr", default=0.001, type=float, help="Initial learning rate.")
    parser.add_argument("--lr_min", default=0.00001, type=float, help="When learning rate decays to lr_min, it stops.")
    #parser.add_argument("--xlnet_model_dir", default='your_path_to_xlnet/xlnet_cased_L-12_H-768_A-12',type=str, help="XLNet model path")
    parser.add_argument("--xlnet_model_dir", default='/home/psxwz2/tony/coding/workspace/xlnet_cyberzhg/pretrained_models/xlnet_cased_L-12_H-768_A-12',type=str, help="XLNet model path")
    parser.add_argument("--checkpoints_dir", default='log', type=str, help="The folder to save checkpoint.")
    parser.add_argument("--outputs_dir", default='outputs', type=str, help="The folder to save test outputs file.")


